spring.application.name=school

spring.datasource.url=jdbc:postgresql://localhost:5432/hogwarts

spring.datasource.username=student
spring.datasource.password=chocolatefrog

spring.datasource.driver-class-name=org.postgresql.Driver


school.avatar.dir.path=avatars

spring.jpa.hibernate.ddl-auto=validate
spring.liquibase.change-log=classpath:liquibase/index-practice.yml
