spring.application.name=school

# ???? ? ???? ?????? hogwarts
spring.datasource.url=jdbc:postgresql://localhost:5432/hogwarts

# ????? ????, ??????? ?? ??????? ?? ??????????
spring.datasource.username=student
spring.datasource.password=chocolatefrog

# ??????? (Spring Boot 3/4 ????????? ??? ???, ?? ????? ?????????????)
spring.datasource.driver-class-name=org.postgresql.Driver

# ????????? ??????????????? ?????????? ??????
spring.jpa.hibernate.ddl-auto=update

